global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'go-app'
    static_configs:
      - targets: ['host.docker.internal:8080']
  
  - job_name: 'redis'
    scrape_configs:
      - targets: [redis:9121]

  - job_name: 'prometheus'
    scrape_configs:
      - targets: ['localhost:9090']